development:
  secret_key_base: 2326a28f72f06885b78a152385202b3df4ce0d6b1520e4bc49ad9ecaa1195141e253008d10cf25a293d7948c1d6d6e010203dfc6e61e7c120277019af962087b
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_phone_number: <%= ENV["TWILIO_NUMBER"] %>
test:
  secret_key_base: 2c08fca341cda993818190a3b2a1b30b62c97f7ed0d674730035e0a28e99791c95cc62e8c2099255cf3c8fe247b78df09b55e87704db1838941d88884efb9c15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_phone_number: <%= ENV["TWILIO_NUMBER"] %>